version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
    commit-message:
      prefix: 'build'
      include: scope

  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
    commit-message:
      prefix: 'build'
      include: scope
    groups:
      dev:
        applies-to: version-updates
        dependency-type: development

  - package-ecosystem: pip
    directory: '/'
    schedule:
      interval: weekly
    commit-message:
      prefix: 'build'
      include: scope
    groups:
      mkdocs:
        applies-to: version-updates
        patterns:
          - 'mkdocs*'
      pytest:
        applies-to: version-updates
        patterns:
          - 'pytest*'
      dev:
        applies-to: version-updates
        dependency-type: development
        exclude-patterns:
          - 'mkdocs*'
          - 'pytest*'
        update-types:
          - patch
          - minor
      prod:
        applies-to: version-updates
        dependency-type: production
        exclude-patterns:
          - 'mkdocs*'
          - 'pytest*'
        update-types:
          - patch
          - minor
