site_name: Portabellas
repo_url: https://github.com/lars-reimann/portabellas
repo_name: lars-reimann/portabellas
edit_uri: edit/main/docs/
site_url: !ENV READTHEDOCS_CANONICAL_URL
strict: true

nav:
  - Home:
    - README.md
    - CHANGELOG.md
  - API Reference: reference/

# Configuration of MkDocs & Material for MkDocs --------------------------------

theme:
  name: material
  logo: img/logo.png
  favicon: img/logo.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: indigo
      accent: indigo

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: black
      accent: indigo
  features:
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.follow

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths:
            - src
          options:
            docstring_style: numpy
            filters:
              - "!^_"  # Hide internal & dunder methods
            inherited_members: true
            show_if_no_docstring: true
            show_labels: false
            show_signature: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            summary: true
  - gen-files:
      scripts:
        - docs/reference/generate_reference_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - autorefs
  - glightbox
  - search
  - exclude:
      glob:
        - "*.csv"
        - "*.py"

watch:
  - src

markdown_extensions:
  # Admonitions
  - admonition
  - pymdownx.details

  # Code blocks
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

  # Diagrams
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  # Footnotes
  - footnotes

  # Keys
  - pymdownx.keys

  # Icons & emojis
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  # Images
  - attr_list
  - md_in_html

  # Lists
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  # MathJax
  - pymdownx.arithmatex:
      generic: true

  # Permalinks
  - toc:
      permalink: true

  # Tabs
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - javascript/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
