name: Dependency Review

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  dependency-review:
    uses: lars-reimann/.github/.github/workflows/dependency-review-reusable.yml@main
