name: Main

on:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        platform:
          - "ubuntu-latest"
          - "macos-latest"
          - "windows-latest"
        python-version:
          - "3.12"
          - "3.13"
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v5

      - name: Install uv and set Python version
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Install project
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        if: ${{ !(matrix.platform == 'ubuntu-latest' && matrix.python-version == '3.13') }}
        run: uv run pytest tests

      - name: Run tests with coverage
        if: ${{ matrix.platform == 'ubuntu-latest' && matrix.python-version == '3.13' }}
        run: uv run pytest tests --cov=portabellas --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        if: ${{ matrix.platform == 'ubuntu-latest' && matrix.python-version == '3.13' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
