name: Pull Request

on:
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.head_ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v5

      - name: Install uv and set Python version
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: "3.13"

      - name: Install project
        run: uv sync --locked --all-extras --dev

      - name: Run tests with coverage
        run: uv run pytest tests --cov=portabellas --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
