name: Release to PyPI

on:
  workflow_dispatch

permissions:
    contents: write
    id-token: write
    issues: write
    pull-requests: write

jobs:
  build:
    strategy:
      matrix:
        platform:
          - "ubuntu-latest"
          - "macos-latest"
          - "windows-latest"
        python-version:
          - "3.12"
          - "3.13"
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v5

      - name: Install uv and set Python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install project
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        run: uv run pytest tests

  release:
    environment: "release"
    runs-on: "ubuntu-latest"
    needs: build
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install uv and set Python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.13"

      - name: Install project
        run: uv sync --locked --all-extras --dev

      - name: Use Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "lts/*"

      - name: Install NPM dependencies
        run: npm ci

      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
